<a href="https://colab.research.google.com/github/VinayakDubey07/Machine-learning/blob/main/ML_LAB_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_iris
from sklearn import tree
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
iris=load_iris()
iris

In [3]:
X=iris.data[:,2:]
y=iris.target

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [5]:
dt=tree.DecisionTreeClassifier()
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [6]:
y_pred=dt.predict(X_test)

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
plt.figure(figsize=(10,10))
tree.plot_tree(dt, filled=True, fontsize=14)

In [ ]:
dt.predict([[5,1.5]])

In [14]:
from sklearn.tree import export_graphviz
export_graphviz(
dt,
out_file="iris.dot",
feature_names=iris.feature_names[2:],
class_names=iris.target_names,
rounded=True,
filled=True
)

In [15]:
%ls

iris1_tree.png  iris.dot  iris_tree.dot  sample_data/


In [16]:
!dot -Tpng iris_tree.dot -o iris1_tree.png

In [ ]:
from IPython.display import Image
Image(filename = 'iris1_tree.png')

In [19]:
from sklearn.metrics import precision_score,recall_score,f1_score,classification_report,confusion_matrix
print("confusion matrix\n", confusion_matrix(y_pred,y_test))
print(classification_report(y_pred,y_test))

confusion matrix
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

